# Inventaire Ansible - Environnement de TP (conteneurs Docker)
[webservers]
web1 ansible_host=localhost ansible_port=2201
web2 ansible_host=localhost ansible_port=2202

[dbservers]
db1 ansible_host=localhost ansible_port=2203

[all_servers:children]
webservers
dbservers

[all_servers:vars]
ansible_user=ansible_user
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
