---
- name: Déployer et configurer Filebeat pour la gestion des logs
  hosts: all_servers
  become: true

  tasks:
    - name: Installer gpg (nécessaire pour apt_key)
      ansible.builtin.apt:
        name: gnupg
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Ajouter la clé GPG d'Elastic (Debian)
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Ajouter le dépôt Elastic (Debian)
      ansible.builtin.apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: elastic-8.x
      when: ansible_facts['os_family'] == "Debian"

    - name: Installer Filebeat (Debian)
      ansible.builtin.apt:
        name: filebeat
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Ajouter le dépôt Elastic (RedHat)
      ansible.builtin.yum_repository:
        name: elastic-8.x
        description: Elastic repository for 8.x packages
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Installer Filebeat (RedHat)
      ansible.builtin.dnf:
        name: filebeat
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Déployer le fichier de configuration filebeat.yml
      ansible.builtin.template:
        src: ../templates/filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0600'
      notify: Redémarrer Filebeat

    - name: Démarrer et activer Filebeat
      ansible.builtin.systemd:
        name: filebeat
        state: started
        enabled: true
      ignore_errors: true

  handlers:
    - name: Redémarrer Filebeat
      ansible.builtin.systemd:
        name: filebeat
        state: restarted
      ignore_errors: true
